IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'Params')
BEGIN
    CREATE TABLE dbo.Params (
		paramid			INTEGER IDENTITY NOT NULL,
		parameter		VARCHAR(50) NOT NULL,
		minval			NUMERIC(10,7) NOT NULL,
		maxval			NUMERIC(10,7) NOT NULL,
		ideal			NUMERIC(10,7) NOT NULL
	 )
END