IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'Patient')
BEGIN
    CREATE TABLE dbo.Patient (
		patientid	INTEGER IDENTITY NOT NULL,
		name		VARCHAR(50) NOT NULL,
		age			INTEGER NOT NULL,
		address		VARCHAR(100),
		PRIMARY KEY(patientid)
	 )
END