IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'Product')
BEGIN
    CREATE TABLE dbo.Product (
		productid	INTEGER IDENTITY NOT NULL,
		product		VARCHAR(50) NOT NULL,
		PRIMARY KEY (productid)
	 )
END